name: CI
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  build:
    strategy:
      matrix:
        preset: [linux-clang, linux-gcc, macos, windows]
        config: [Debug, Release]
        include:
          - preset: linux-clang
            os: ubuntu-latest
          - preset: linux-gcc
            os: ubuntu-latest
          - preset: macos
            os: macos-latest
          - preset: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: choco install -y openssl

      - name: Find OpenSSL on macOS
        if: runner.os == 'macOS'
        run: echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --config ${{ matrix.config }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }} -C ${{ matrix.config }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-install --config ${{ matrix.config }}
