name: Latest

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the latest CA certificate
        shell: cmake -P {0}
        run: |
          file(
              DOWNLOAD https://curl.se/ca/cacert.pem ${CMAKE_CURRENT_BINARY_DIR}/cert.pem
              EXPECTED_HASH SHA256=23c2469e2a568362a62eecf1b49ed90a15621e6fa30e29947ded3436422de9b9
          )
