name: Latest

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the latest CA certificate
        shell: cmake -P {0}
        run: |
          file(
              DOWNLOAD https://curl.se/ca/cacert.pem ${CMAKE_CURRENT_BINARY_DIR}/cert.pem
              EXPECTED_HASH SHA256=189d3cf6d103185fba06d76c1af915263c6d42225481a1759e853b33ac857540
          )
